; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Book Tracker"
#define MyAppVersion "6.5"
#define MyAppPublisher "Chief Guy"
#define MyAppURL "https://github.com/cheeesed123"
#define MyAppExeName "runMe.bat"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".exe"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt
#define path "C:\Users\ollie\Desktop\Code Projects\Java\School\Book-Tracker"
[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{CC0289EE-5743-4CB3-9C4D-D3A19F1C33E2}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile="{#path}\LICENSE.txt"
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=BTSetup
SetupIconFile="{#path}\logo.ico"
SolidCompression=yes
WizardStyle=modern dynamic
OutputDir=..\Book-Tracker

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#path}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#path}\runtime\*"; DestDir: "{app}\runtime"; Flags: ignoreversion recursesubdirs
Source: "{#path}\Documentation\*"; DestDir: "{app}\Documentation"; Flags: ignoreversion
Source: "{#path}\lib\books.csv"; DestDir: "{app}\lib"; Flags: ignoreversion
Source: "{#path}\src\Book-Tracker.jar"; DestDir: "{app}\src"; Flags: ignoreversion
Source: "{#path}\src\thanks!.txt"; DestDir: "{app}\src"; Flags: ignoreversion isreadme
Source: "{#path}\README.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#path}\runMe.*"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#path}\logo.ico"; DestDir: "{app}"; Flags: ignoreversion

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autodesktop}\Book Tracker"; Filename: "{app}\runMe.bat"; IconFilename: "{app}\logo.ico"
Name: "{group}\Book Tracker"; Filename: "{app}\runMe.bat"; IconFilename: "{app}\logo.ico"

